Net/ThemeName "breeze"
Net/IconThemeName "papirus"
Gtk/CursorThemeName "bibata-modern-classic"
Net/EnableEventSounds 1
EnableInputFeedbackSounds 1
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
