# Colors
include								colors.conf
include								theming.conf

# Shell settings
shell									/usr/bin/zsh
editor								/usr/bin/nvim

# Font
font_family						family="JetBrains Mono"
bold_font	 						auto
italic_font	 					auto
bold_italic_font			auto
font_size							10

# Audio bell
bell_path							grillito.ogg

# Mouse
mouse_hide_wait				3.0

# Window
background_blur				1

# Necessary for wallpaper script
allow_remote_control	true

# Seems to not get that automatically
linux_display_server	x11

