# Programs
# Set commonly used apps
$terminal = kitty
$cleanTerminal = kitty --config ~/.config/kitty/clean.conf bash

$filemanager = dolphin
$menu = rofi -show drun -show-icons 
$browser = firefox

$screenshot = hyprshot -m region -o "$HOME/Downloads"

$toggleStatusbar = $HOME/.config/scripts/toggle-statusbar.sh
